apiVersion: v1
kind: Secret
metadata:
  name: myapp-tls
  namespace: default
  labels:
    app: myapp
  annotations:
    kubernetes.io/tls-acme: "true"
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>