- hosts: k8s
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - curl
          - docker.io
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - docker
        - kubelet